### ISSUE TITLE
Will it work?

### ISSUE THREAD

**Issue by mcnaveen** [scossar/wp-discourse-export#1]
I want to migrate my existing comments to discourse. Will it work?

**Comment by scossar** [comment]
It's been three years since I looked at this code. I can't recommend using it. It could be useful example code though. It's possible that it will work for you. You may run into timeout issues with API calls made to Discourse though. If you do end up using the plugin, make sure you remove it from your WordPress site after having run the export - the plugin is unmaintained, so isn't getting security updates.

**Comment by mcnaveen** [comment]
Okay. Let me try and update here.
